### ISSUE TITLE
关系运算符中的re有实现吗

### ISSUE THREAD

**Issue by zzwtop1** [failgoddess/ruleEngine#2]

**Comment by failgoddess** [comment]
有实现,加微信细聊吧18733123202




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "failgoddess/ruleEngine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 下午5:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [failgoddess/ruleEngine] 关系运算符中的re有实现吗 (Issue #2)





 
Reopened #2.
